services:
  postgres:
    image: postgres:16-alpine
    container_name: ticketing_postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: ticketing_db
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"

  redis:
    image: redis:7-alpine
    container_name: ticketing_redis
    restart: always
    ports:
      # *# Suggestion: change to "6379:6379" if you don't have Redis already installed/running on your machine
      - "6380:6379"
    volumes:
      - "redis_data:/data"

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: ticketing_rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"

  k6:
    image: grafana/k6:latest
    container_name: ticketing_k6
    network_mode: host
    volumes:
      - "./tests/load:/scripts"
    environment:
      - API_URL=${API_URL:-http://localhost:3000}
      - TIER_ID=${LOAD_TEST_TIER_ID}
    profiles: ["tools"]

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data: